### ISSUE TITLE
BeerJS Cba Meetup No. 2

### ISSUE THREAD

**Issue by loverajoel** [beerjs/cordoba#1]
Se viene una nueva BeerJS y en esta oportunidad lo realizaremos en la oficina de Olapic con cerveza y pizza gratis!, hora: desde las 18:30hs

BeerJS es un evento que nació en San Francisco y consiste en juntarnos en un espacio distendido a hacer networking y conversar de lo que más nos gusta: Javascript.

En esta edición proponemos charlar de los siguiente tópicos: ReactJS, Angular, Ecma6, Ember u otros. Tenemos todas las comodidades en la oficina y contamos con equipos para aquellos que quieran dar sus charlas o presentar trabajos.

Por favor confirmen su asistencia si están seguros de poder venir así nos aseguramos el número correcto de provisiones!

Los esperamos!

(Aviso: La plataforma Meetup para organizar eventos es muy buena, pero tiene un limite free de 50 miembros, como ya llegamos a ese límite, la comunidad tiene un perfil en Github y las siguientes Meetups las organizamos por ahí.)

**Comment by loverajoel** [comment]
Alguien esta jugando con ECMA6, ReactJS, Angular2?

**Comment by marcemira** [comment]
Porque me discriminan a ember.js?

**Comment by sergiolepore** [comment]
@loverajoel ES6+ (o ES2015+ o whatever) por acá.

**Comment by loverajoel** [comment]
@marcemira @sergiolepore próximo Meetup el viernes 29 de mayo? Olapic pone el lugar y las cervezas, que les parece?

**Comment by marcemira** [comment]
@loverajoel Dale de una.

**Comment by sergiolepore** [comment]
@loverajoel @marcemira de una!

**Comment by BrodaNoel** [comment]
Yo voy gente!

**Comment by sercba** [comment]
Hola chicos, soy nuevo en el grupo y me gustaría comenzar a participar. Sigo por acá las novedades, por ahora podría ir el viernes a las 19 en Kambaku. Saludos!

**Comment by loverajoel** [comment]
Descripción del evento actualizada, nos vemos el viernes! compartamos así juntamos gente!

**Comment by martinbavio** [comment]
¡Voy!

**Comment by pablocelayes** [comment]
¿Alguien por acá ha andado haciendo visualizaciones con D3.js?

Estamos organizando encuentros de Data Science y nos vendría muy bien que alguien con experiencia en el tema se arrime a compartir algo al respecto.

**Comment by Cosmitar** [comment]
si hola @loverajoel, yo quería saber si un gorgojo en el maní es considerado un bug

**Comment by marcemira** [comment]
Hora? salgo de laburar a las 2pm y a la noche tengo que hostear el #emberñoquis XD

**Comment by loverajoel** [comment]
@marcemira a las 18:30hs largamos, te esperamos un rato aunque sea

**Comment by marcemira** [comment]
@loverajoel :+1:

**Comment by horacioliva** [comment]
@pablocelayes Estamos usando algo de D3 en nuestros dashboard de analytics aca en Olapic. Voy a ver si puedo hacer que alguno de los chicos que le esta dando rosca se quede para que charlen.

Salu2

**Comment by pablocelayes** [comment]
Buenísimo, muchas gracias @horacioliva !

Si pueden, dense una vuelta por el próximo encuentro y charlamos ahí:

http://www.meetup.com/Encuentros-Data-Science-Cordoba/events/220559776/

Saludos!

**Comment by avilaton** [comment]
Hola amigos,

este sábado 19 de septiembre organizamos una escuela para aprender JAVASCRIPT en el laboratorio de fabricación digital CREA. 

La escuela estará basada en las nodeschool, usaremos node.js para aprender a escribir programas que pueden correr como 
- servidores web
- interfaces a Arduino/raspberry.py y otras, (los que tengan esos bichos pueden traerlos)
  entre otras cosas. La idea del evento es que cada uno pueda hacer un poquito de experiencia y trabajar entre pares. Nada muy formal.

No es requerimiento, pero si pueden traer instalado node.js es mucho mejor. Habrá WIFI gratis.

El laboratorio está frente a la plaza colon (Nicolas Avellaneda 282) y tiene muchas cosas interesantes para que vean, como impresoras 3d, cortadoras laser y un router cnc.

Les pido por favor que vengan, y que me confirmen que lo harán. Queremos probar este tipo de evento para hacerlo más grande la próxima vez.

Saludos y no duden en escribir por cualquier duda.
CC: @alejandrocragnolini-santex

**Comment by thematho** [comment]
Hora?

**Comment by avilaton** [comment]
Disculpas. De 10 a 17 hs. Al mediodía haremos unos choripanes para los que quieran.

**Comment by AtilaDev** [comment]
Un, me la perdí! Encima vivo recerca. La próxima voy!
