### ISSUE TITLE
Electron for beginners by a beginner

### ISSUE THREAD

**Issue by mdottavio** [beerjs/cordoba#10]
Introducción a Electron - De cero a una app nativa usando Electron, Webpack y React.

## Author
@emiprandi

**Comment by mdottavio** [comment]
Charla realidad en la edición 9
https://www.meetup.com/Beer-js-Cordoba/events/240478735/
🍻

**Comment by emiprandi** [comment]
🍺  [Slides](https://docs.google.com/presentation/d/1akSf2e-wes6TW0TELFoysULVTuw5VPZOeP5iB5qDy_Y/edit?usp=sharing) y [Demo App Repo](https://github.com/emiprandi/trakker)
