### ISSUE TITLE
Construye una API Rest en pocos Minutos con Serverless Framework

### ISSUE THREAD

**Issue by mdottavio** [beerjs/cordoba#11]
La idea es presentar un ejemplo  de como construir un par de enpoints tipo Hello world (un POST y un GET) usando Serverless Framework y desplegarlo en AWS  Lambda + api gateway.

## Author
@dolguin-

**Comment by mdottavio** [comment]
Charla realidad en la edición 9
https://www.meetup.com/Beer-js-Cordoba/events/240478735/
🍻

**Comment by dolguin-** [comment]
I am @dolguin- :wink:
