### ISSUE TITLE
Creación del chapter Nodeschool Córdoba

### ISSUE THREAD

**Issue by avilaton** [beerjs/cordoba#2]
Se solicitó la creacion del chapter de nodeschool para cordoba. Ahora necesitaria un poco de cariño la página que se forkeo de buenos aires.
http://nodeschool.io/cordoba/
Se aceptan PR. Alguna idea de que le podemos hacer/agregar?
https://github.com/nodeschool/cordoba

**Comment by sergiolepore** [comment]
+1! Quiero colaborar!

**Comment by nestornav** [comment]
+1 estoy interesado

**Comment by ataschz** [comment]
Che, y si le dos difusión vía Twitter? Yo también quiero colaborar! Voy a tirar un PR!

**Comment by ataschz** [comment]
Si le damos* era.. jaja

**Comment by joelalejandro** [comment]
+1, también interesado

**Comment by elmiguedev** [comment]
+1 !!

**Comment by nestornav** [comment]
+1

**Comment by avilaton** [comment]
https://github.com/nodeschool/cordoba
