### ISSUE TITLE
Intro y conceptos básicos a React Native + Expo

### ISSUE THREAD

**Issue by mdottavio** [beerjs/cordoba#20]
La charla será introductoria. Ventajas de React Native frente a otros frameworks híbridos similares. Intro al framework Expo, ventajas y desventajas de usarlo.

## Author
@leandrocba

**Comment by homer0** [comment]
**UPDATE:** @marcomaza92 estuvo hablando con Leandro y no va a estar disponible por un buen tiempo, así que cerramos el issue; cuando se libere, si hay posibilidad de darla, lo abrimos de nuevo.
