### ISSUE TITLE
Intro a MeteorJS

### ISSUE THREAD

**Issue by mdottavio** [beerjs/cordoba#21]
Presentacion de Meteor Fullstack Platform, Principios, Reactividad, Isomorfismo, Pub/Sub, Compensación de Latencia, Real Time

## Author
@danilo

**Comment by danilopaez** [comment]
Mauri...esta charla ya la hicimos...si queres cerrala...abz

**Comment by mdottavio** [comment]
@danilopaez 👍 busco el link a la meetup y la cierro :)

**Comment by homer0** [comment]
Charla realizada en la [edición 10](
https://www.meetup.com/Beer-js-Cordoba/events/241602322/) 🍻
