### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by mdottavio** [beerjs/cordoba#22]
JS en el telefono sin perder performance o comodidad

## Author
@mmiani

**Comment by mdottavio** [comment]
Hola @mmiani, consulta como vez presentar esta charla en el beerjs de diciembre? Sería el 14 (semana que viene.)

**Comment by asermax** [comment]
@mdottavio Marcos se fué para Holanda a finales del año pasado así que creería que este ticket se puede cerrar :stuck_out_tongue:

**Comment by mdottavio** [comment]
Gracias por la data @asermax !
