### ISSUE TITLE
BootBot: Desarrollando chatbots para Messenger con Node.js

### ISSUE THREAD

**Issue by Charca** [beerjs/cordoba#25]
Introducción y ejemplos de desarrollo de chatbots para Facebook Messenger con JavaScript utilizando el framework [BootBot](https://github.com/Charca/bootbot).

# Author
@Charca

**Comment by mdottavio** [comment]
@Charca gracias por tu colaboración; como lo vez para presentarla en la beerjs de diciembre? sería el 14 (semana que viene).

**Comment by Charca** [comment]
Gracias @mdottavio! Dale, puedo preparar algo para la semana que viene 👍

**Comment by mdottavio** [comment]
Groso! seguimos por Slack (por si necesitas algo).

**Comment by mdottavio** [comment]
Charla realidad en la edición 15
https://www.meetup.com/Beer-js-Cordoba/events/245725640/
🍻
