### ISSUE TITLE
Elección del stack y dockerización del enviroment de desarrollo

### ISSUE THREAD

**Issue by s4nt14go** [beerjs/cordoba#26]
Vengo desarrollando un proyecto que es una app para el celu que se conecta a la centralita del auto y envía los datos para monitoreo remoto vía web y hago una charla sobre mi experiencia.

Son temas comunes que se pueden aplicar a cualquier proyecto:

* ¿Por qué elegí el stack de desarrollo con el que implemento?
* Ventajas de establecer un enviroment de desarrollo común a todos los programadores.
* Dockerización del enviroment. Comandos comunes de docker para usar la imagen del enviroment.
* Video demo de lo desarrollado en el proyecto hasta ahora.

**Comment by mdottavio** [comment]
Charla realidad en la edición 17
https://www.meetup.com/Beer-js-Cordoba/events/248569221/
🍻
