### ISSUE TITLE
Dynamic Imports - Importacion Dinamica de Modulos JS en el Cliente

### ISSUE THREAD

**Issue by danilopaez** [beerjs/cordoba#27]
Es una estrategia de carga dinámica de Modulos JS en el cliente(Browser) con el fin de optimizar la carga inicial y mejorar el pageload time. Esto se logra disminuyendo el tamaño del “Bundle” a descargar al inicio; postergando los modulos pesados y secundarios (Lazy Loading).

https://github.com/tc39/proposal-dynamic-import

**Comment by mdottavio** [comment]
Queda para la edición de Mayo 2018!
Gracias @danilopaez

**Comment by homer0** [comment]
@mdottavio ping (to close)

**Comment by mdottavio** [comment]
Charla realizada en la edición 18
https://www.meetup.com/Beer-js-Cordoba/events/250653720/
🍻
