### ISSUE TITLE
El desafío de mover un gran elfante de gelatina

### ISSUE THREAD

**Issue by tauchter** [beerjs/cordoba#28]
Queremos compartir el camino recorrido, las lecciones aprendidas que tuvimos que como empresa para migrar gran parte de nuestro stack a Node, Express y ReactJS. Como también el impacto que esto tuvo en la development experience y la performance.

**Comment by homer0** [comment]
@mdottavio ping (to close).

**Comment by mdottavio** [comment]
Charla realidad en la edición 18
https://www.meetup.com/Beer-js-Cordoba/events/250653720/
🍻
