### ISSUE TITLE
BeerJS Cba Meetup No. 3

### ISSUE THREAD

**Issue by loverajoel** [beerjs/cordoba#3]
Hola gente, que les parece si organizamos una nueva juntada?
La verdad es que en las primeras dos la convocatoria no fue de la mejor (6,7 personas).
Que les parece que podemos cambiar para que sea mas atractivo y la gente se sume?.
Tal vez es cuestión de difundirlo mejor, puede ser.
Me gustaría que no quede en el aire y hagamos un par antes de fin de año.

**Comment by loverajoel** [comment]
tal vez seleccionar 3 4 expositores, que sin tener que organizar una charla formal, puedan hablar sobre algún tema en particular

**Comment by thematho** [comment]
+1 con que sean 3-4 expositores.
Tengo algunas sugerencias de topics, pero no estoy seguro si alguien
quisiera darlos
- Angular 2.0 and Typescript
- Ecmascript 2015 / 2016 features
- Decorators
  - Immutables types
  - promises
  - Observables
  -  async functions
- Google V8 compiler performance

Saludos

**Comment by loverajoel** [comment]
@thematho la seguimos acá, ahora somos premium y podemos conversar todos.
http://www.meetup.com/Beer-js-Cordoba/messages/boards/thread/49298582/0/#128528561

**Comment by mdottavio** [comment]
cerrando esto porque viejo :)
