### ISSUE TITLE
Vue.js on legacy systems === 💚

### ISSUE THREAD

**Issue by ataschz** [beerjs/cordoba#32]
Charla orientada a un **nivel medio** en Vue.js + Vuex. La idea principal es mostrar un caso de estudio real con el uso de una arquitectura Front-End moderna embebida en un sistema legacy, desarrollado en JQuery y PHP. La misma estaria basda en una SPA Vue.js moderna, y el manejo de estado de la aplicación mediante Vuex.

Topicos:
- **Case study:** Presentación del caso de estudio y motivación de esta charla.
- **Progressive Front-End Architecture:** Explicación de como resolvimos los desafíos técnicos de nuestro legacy system?
- **True progressive integration:** ¿Que significa que un framework sea progresivo?
- **Questions:** Preguntas sobre nuestra experiencia?

**Comment by mdottavio** [comment]
Charla realizada en la edición 20
https://www.meetup.com/Beer-js-Cordoba/events/252837707/
🍻
