### ISSUE TITLE
TIDD: Trabajo Independiente Driven Development

### ISSUE THREAD

**Issue by martinbavio** [beerjs/cordoba#33]
## Titulo
TIDD: Trabajo Independiente Driven Development

## Descripción
¿Se puede trabajar como developer desde casa dejando el ambiente de oficina y los perks que te ofrece la empresa de moda local, y no morir en el intento? La mayoría soñamos con eso, pero no sabemos como llevarlo a cabo. La idea de la charla es ofrecer experiencias de desarrolladores que hayan intentado hacerlo y aún esten vivos para contarlo. Tips, consejos, y ping-pong de preguntas y respuestas incluído. 

## Sobre el orador
La idea es que no sea uno solo, sino que se arme un estilo panel, de no más de 4 personas. Estaría bueno que aquellos que se ofrezcan dejen un comentario en este issue contando por que creen que su experiencia puede ser útil para el resto. Luego los agrego a la siguiente lista de oradores:

- [@mbavio](http://martinbavio.com): creo que mi experiencia puede ser útil porque hace casi 10 años que trabajo para el exterior haciendo diseño y desarrollo web. He pasado por distintos momentos en cuando a lo laboral, lo económico y lo personal, momentos que creo son patrones comunes del trabajo remoto, y son necesarios poder reconocer para que la experiencia no se termine convirtiendo en una pesadilla. 
- [@BrodaNoel](https://github.com/BrodaNoel/cv): hace 6 meses que tomé la decision (me la hicieron tomar a la fuerza) de ponerme a laburar como freelo. Opté por hacer la transicion de una forma progresiva. Rapida, pero progresiva. Controlada y asesorada. Tengo todos los recuerdos bien frescos porque todo sucedió hace poco tiempo. Mi experiencia podria ayudar a responder un par de preguntas relacionadas a AFIP, contaduría, y cuestiones legales, como asi también a "¿cómo hacer este salto de manera progresiva?".
- [@Charca](https://github.com/Charca): hace 3 años que trabajo remoto full-time para una empresa de USA, antes de eso trabajé en Globant durante 5 años, aprendiendo mucho pero también renegando un montón (más que nada con la plata). Puedo hablar sobre las ventajas y desventajas del trabajo remoto, sobre viajar trabajando, y cómo fue el proceso de pegar el salto de una empresa a la otra (en mi caso el salto no fue progresivo sino más de un día para el otro).

## Recursos
- **Slides**: Quizás podamos armar algo en común para dividir en _secciones_ la charla, algo a consensuar entre los oradores también.

## Extra
- **¿Tenés la charla preparada?** No, pero tengo una idea de como podría transcurrir, que me gustaría acordar también con aquellos que se propongan de oradores.
- **¿En que mes la podrías dar?** Cuando haya disponibilidad y todos los oradores podamos.

**Comment by BrodaNoel** [comment]
Hace 6 meses que tomé la decision (me la hicieron tomar a la fuerza) de ponerme a laburar como freelo. Opté por hacer la transicion de una forma progresiva. Rapida, pero progresiva. Controlada y asesorada. Tengo todos los recuerdos bien frescos porque todo sucedió hace poco tiempo. Mi experiencia podria ayudar a responder un par de preguntas relacionadas a AFIP, Contaduria, y cuestiones legales, como asi tambien a "cómo hacer este salto de manera progresiva?"

**Comment by tretapey** [comment]
Puedo participar? en realidad no trabajo como freelance sino que fundé mi propia empresa y marca, y ahora estoy armando la segunda.. creo que hay una diferencia grande entre eso y el trabajo freelance.

**Comment by Charca** [comment]
Hace 3 años que trabajo remoto full-time para una empresa de USA, antes de eso trabajé en Globant durante 5 años, aprendiendo mucho pero también renegando un montón (más que nada con la plata). Puedo hablar sobre las ventajas y desventajas del trabajo remoto, sobre viajar trabajando, y cómo fue el proceso de pegar el salto de una empresa a la otra (en mi caso el salto no fue progresivo sino más de un día para el otro).

**Comment by nnicolopez** [comment]
Yo estoy buscando dar ese paso así que de antemano agradezco a todos los que van a compartir sus experiencias. Puede ser de mucha ayuda y seguro no soy el único en el grupo en esta situación..

**Comment by niceforo1** [comment]
@nnicolopez exacto yo estoy en la misma situación intentado de dar ese paso, estaría bueno que puedan compartir sus experiencias!.

**Comment by martinbavio** [comment]
@Charca Agregado a la descripción!

@tretapey Me parece interesante tu aporte porque es otra vertical de la misma idea, y seguramente podes aportar en cosas sobre como crear una empresa en este pais, con todos los aspectos legales y financieros que eso implica. ¿Que opina el resto?

**Comment by BrodaNoel** [comment]
+1 al aporte de Tretapey

**Comment by martinbavio** [comment]
@tretapey ¿Podrias escribir una breve descripción de que le sumarias a la charla asi lo agrego en el mensaje inicial?

**Comment by eamanu** [comment]
ME parece una excelente idea!!

**Comment by tretapey** [comment]
@mbavio antes necesitaría saber cuándo es para ver si voy a poder estar...

**Comment by BrodaNoel** [comment]
Dejo aca anotado para que no nos olvidemos de hablar de estos temas:
* La importancia de tener conocimientos sobre Metogolodias Agiles, laburar en equipo, en equipos remotos.
* La importancia de saber Ingles.

**Comment by mdottavio** [comment]
Charla realizada
https://www.meetup.com/Beer-js-Cordoba/events/252125977/
🍻
