### ISSUE TITLE
JavaScript Fundamentals - Array Methods

### ISSUE THREAD

**Issue by mdottavio** [beerjs/cordoba#35]
@battaglr podes agregar un poco de descripción? 
Gracias 🍺 

Generado en #30

**Comment by battaglr** [comment]
Hice un enroque de esta por la de Scope. ¿Te parece que lo cerremos y abramos después si decido retomarla?

**Comment by joelalejandro** [comment]
Yo no tengo problema en dar esta charla en algún momento :)

**Comment by mdottavio** [comment]
@joelalejandro 👍

**Comment by ElRodrigote** [comment]
Estuve hablando con homer0 y voy a dar esta charla en la BeerJS del 22/11/2018.
Voy a hablar de todos los métodos pero voy a hacer foco particular en map(), filter() y reduce(); un par de ejemplos y comparaciones de performance entre esos métodos (map y filter contra reduce; y los 3 contra los for methods), y probablemente compare métodos nativos contra métodos de librerías (particularmente lodash).

Cuando lo tenga un poco más ordenado lo completo mejor.

**Comment by elmiguedev** [comment]
acordate de los forssss xD

**Comment by joelalejandro** [comment]
@ElRodrigote Estaría bueno también mencionar cosas como every() y some() :D

**Comment by ElRodrigote** [comment]
Link a los slides, hay unos cuantos speaker notes que pueden revisar si quieren también:

https://slides.com/rodrigoali/deck/live#/
