### ISSUE TITLE
JavaScript Fundamentals - Async: Callbacks => Promises => Async/Await 

### ISSUE THREAD

**Issue by mdottavio** [beerjs/cordoba#36]
@joelalejandro podes agregar más detalles? 
Gracias 🍺 

Generado en #30

**Comment by joelalejandro** [comment]
La idea es, a grandes rasgos:

- comentar cómo fue evolucionando la forma de manejar paralelización y ejecución en secuencia desde los clásicos `cb()` hasta los modernosos `async/await`.
- hablar de patrones y antipatrones (`callback hell`, `promise hell`)
- cosas copadas que se pueden hacer con Array.map + Promise.all

y lo más importante: por qué necesitamos saber de estas cosas.

**Comment by mdottavio** [comment]
Slides: https://slides.com/joelalejandrovillarrealbertoldi/js-fundamentals-async

Charla realizada en la edición 21
https://www.meetup.com/Beer-js-Cordoba/events/253620694/
🍻
