### ISSUE TITLE
JavaScript Fundamentals - Classes

### ISSUE THREAD

**Issue by mdottavio** [beerjs/cordoba#37]
@HGARZON podes agregar más detalles?
Gracias 🍺 

Generado en #30

**Comment by HGARZON** [comment]
La idea es contar lo siguiente:

- De que se trata una clase,
- Como se hace en JS con ES5,
- Como se hace en JS con ES6

Cortito y al pie.

**Comment by mdottavio** [comment]
@HGARZON Gracias por completar la ide. 
Pregunta, es muy judago preparala para el jueves que viene?

**Comment by HGARZON** [comment]
Si, puedo tener un draft de la charla. Cuando la daría?

**Comment by mdottavio** [comment]
@HGARZON estamos pensando en el jueves 19 de julio; (próximo jueves); recordá que no tiene que ser de más de 15min y más que nada ejemplos :D

**Comment by elmiguedev** [comment]
Si se quiere retomar esta charla, agregaría cómo manejar los conceptos de herencia y polimorfismo (de la forma mas limpia posible xD), buenas practicas para el manejo de clases (bajo acoplamiento, estándares para nomenclatura de clases y propiedades/métodos, visibilidad de props y métodos (entiendo que no hay public y private, pero que se puede manejar de alguna forma)

**Comment by mdottavio** [comment]
@HGARZON @mmoyano16 si les parece bien, pueden organizar la charla en conjunto. Pueden usar Slack como punto de contacto.

**Comment by HGARZON** [comment]
Estaría bien! Cuando sería la próxima Beer JS? Estuve ausente porque estoy con temas de Acamica + el trabajo regular.

**Comment by mdottavio** [comment]
Estamos organizando para el 22 de este mes, sino lo podemos dejar para diciembre (así no estan tan a las corridas)

**Comment by HGARZON** [comment]
Buenas! El sábado 22 no voy a estar en Córdoba. Si querés @mmoyano16 tomarlo vos o bien lo podemos dejar para Enero que si voy a estar.

**Comment by homer0** [comment]
Charla realizada en la [edición 29](
https://www.meetup.com/Beer-js-Cordoba/events/260707969/) 🍻
