### ISSUE TITLE
[PLACEHOLDER] Stories Points: Ninguna verdad, muchas experiencias

### ISSUE THREAD

**Issue by BrodaNoel** [beerjs/cordoba#39]
@brodanoel se dispone a contar de sus experiencias laburando con Story Points.
Se va a describir el sufriento desde el punto de vista dev.

Broda nos va a contar como pasó de ser un super-ninja-hater de los Story Points, a extrañarlos por las noches.

**EDIT: Won't fix**

**Comment by homer0** [comment]
@BrodaNoel http://bit.ly/2AV9qsz

**Comment by BrodaNoel** [comment]
@homer0 ?

**Comment by homer0** [comment]
@BrodaNoel Crei que era claro enough :P, parece mas una charla sobre agile eso.

**Comment by BrodaNoel** [comment]
@homer0 yo puse esto porque la gente lo pidió en el Slack! Pero si no gusta, no la hago. Aca manda usted

**Comment by homer0** [comment]
@BrodaNoel "Aca manda usted", xD, ponele. Na, me parecio que pegaba muy fuera del tarro esto. Si hay quorum, y con la falta de gente con ganas de dar charla... :P.

Pero again, no es que no me guste (eso es altamente relativo xD), es medio random con respecto a la tematica.

No te me ofendas!

**Comment by BrodaNoel** [comment]
@homer0 jamas me ofenderia de un comentario suyo!
