### ISSUE TITLE
Executor

### ISSUE THREAD

**Issue by crystian** [beerjs/cordoba#41]
Que tal? estuve en cordoba y participe en algunas de las meetups que organizan, me volvi a bsas lamentablemente :(, ahora estoy trabajando en un proyecto open https://github.com/crystian/executor ya esta terminado (solo falta la doc en ingles), y casualmente planeo ir del 16 al 23 por esas hermosas tierras, tienen planeada hacer una meet? duraria 20 a 30 min la potencial charla, esto lo di hace unas semanas: https://youtu.be/6SRT0IIj08Y?t=1h52m25s (seria lo mismo pero mas enfocado y prolijo)

**Comment by mdottavio** [comment]
hola @crystian estamos planeando el próximo meetup el 16 de Agosto (19hs); 
es muy jugado llegar de bs as y acercate al lugar donde nos juntemos?
Si te parece bien, joineate a nuestro slack y hablamos por privado:
https://beerjscba.herokuapp.com/

Saludos

**Comment by mdottavio** [comment]
Slides: https://docs.google.com/presentation/d/1sLnBM8J4O8ebieEbwm_ZXGckhGryuCB72HyVG9nhP4E/edit?usp=sharing

**Comment by mdottavio** [comment]
Charla realizada en la edición 21
https://www.meetup.com/Beer-js-Cordoba/events/253620694/
🍻
