### ISSUE TITLE
Machine Learning: Intro + Javascript lib

### ISSUE THREAD

**Issue by elmiguedev** [beerjs/cordoba#42]
Buenas!

La idea surge de la charla anterior en las que algunos preguntaban sobre ML. Si bien todos tenemos una vista general de para que sirve, estaría bueno dar una introducción bien explicada sobre qué es y para qué sirve realmente, y saber sobre algunas herramientas que se pueden utilizar (sin tenerle tanto miedo xD)

En la facu vimos algo de eso, hice un par de cosas (simples aclaro) así que si quieren puedo armar algo de eso (no vi ninguna issue de ML asi que, why not). 

Aclaro, no soy experto! estoy en la misma que el grupo en gral xD, pero me le animo 💪 

La idea seria:

    - introducción a Machine Learning: qué es y fundamentos básicos para poder empezar a googlear al respecto.
    - diferentes técnicas ML
    - redes neuronales 
    - mini ejemplo de alguna técnica de ML (seguramente, Redes Neuronales)
    - qué hay en JS para esto? 

P.D.: no se que onda el tiempo para esto, ML es mucho como para meter todo en una sola charla, si aceptan la charla, voy viendo que puede entrar para los 20 min y de ultima se abre otra issue para expandir el tema.

cha'

**Comment by elmiguedev** [comment]
@mdottavio ponganle el label que no puedo xD

**Comment by mdottavio** [comment]
@mmoyano16 pinta muy bien esta charla!
con respecto al tiempo, se me ocurre que hacer los primeros tres puntos async; tirando la data en el canal de slack; podemos armar un channel temporal donde ir dejando información así la gente que esta interesada en el tema se va metiendo de a poco; luego centras tu charla en los últimos dos puntos.

Que te parece?

**Comment by elmiguedev** [comment]
De una. Seria armar un channel solo de M.L en general? o metemos link interesantes y esas cosas sobre ML en el channel para eso? (no me acuerdo el nombre xD)

**Comment by BrodaNoel** [comment]
Te tiro un dato porque si queres probar algo:
Firebase (Google) lanzó una nueva feature (beta, creo) para hacer ML.
Segun tengo entendido te abstraen al 100% de lo que realmente es Machine Learning y solo te dejan usar ciertas implementaciones de.
Ejemplo: "Agrega ML a tu App: Sube una foto aqui y te detectaremos la cantidad de personas que hay en la foto, o si es de algun lugar famoso, etc etc".

Esta bueno porque te da todo masticado, pero te limita a una par de features, tipo "Deteccion de rostros", "Deteccion de codigos QR", etc. La mayoria son procesamiento de imagenes, y no de datos.
Doc: https://firebase.google.com/products/ml-kit/

**Comment by mdottavio** [comment]
Charla realizada en la edición 22
https://www.meetup.com/Beer-js-Cordoba/events/254650640/
🍻
