### ISSUE TITLE
Microservicios con Node.js

### ISSUE THREAD

**Issue by jbrizio** [beerjs/cordoba#43]
La charla sería una breve introducción al concepto de microservicios. Se podría comentar nuestro caso puntual acá en Naranja y cómo hemos llevado adelante el desarrollo de microservicios haciendo uso de Node.js.

**Comment by mdottavio** [comment]
Charla realizada en la edición 22
https://www.meetup.com/Beer-js-Cordoba/events/254650640/
🍻
