### ISSUE TITLE
JavaScript Fundamentals - Scope & Closures

### ISSUE THREAD

**Issue by battaglr** [beerjs/cordoba#44]
Junto con @nachomena vamos a estar hablando un poco de *Scope* y *Closures*.

A grandes rasgos este sería el temario:

- ¿Qué es el *scope* y cómo funciona? 
- *Scope* global y local.
- *Scope* de function y block.
- *Hoisting*.
- *Closures*.

La charla va a ser bastante dinámica, apoyada en muchos ejemplos, recomendaciones y curiosidades.

---

Parte de la serie JavaScript Fundamentals #30.

**Comment by dolguin-** [comment]
@mdottavio si no me equivoco esta charla ya se dio

**Comment by mdottavio** [comment]
Charla realizada en la edición 22
https://www.meetup.com/Beer-js-Cordoba/events/254650640/
🍻
