### ISSUE TITLE
Programación Lógica y JS - complemento de ambos mundos y motor de inferencia

### ISSUE THREAD

**Issue by dgutson** [beerjs/cordoba#46]
La idea de esta charla es traer un poco el paradigma de programación lógica en general (y prolog en particular) hacia la comunidad de JavaScript, como otra herramienta para encarar problemas de una manera distinta.
Proponemos contar además cómo podría ser un inference engine usando ES5.

**Comment by homer0** [comment]
@dgutson todavía estas interesado en dar la charla? avisanos.

**Comment by dgutson** [comment]
@homer0  No :( Me encantaría pero no doy abasto ni con mi propia familia...

**Comment by homer0** [comment]
@dgutson no problem chango! avisa cualquier cosa y re abrimos el issue.
