### ISSUE TITLE
Desarrollo de juegos con JS (phaser)

### ISSUE THREAD

**Issue by elmiguedev** [beerjs/cordoba#50]
Buenas!

La idea seria mostrar la posibilidad de desarrollar juegos en JS tanto para browser como para mobile (incluso creo que desktop tmb), y que tan potente puede ser.

No sé si se dio o se habló de algo así, pero q más da, está bueno el tema

@mmaza 

PD: se podría complementar con Socket.IO

Edit: 
-----------

Mas allá de que esté cerrada la issue, dejo info sobre phaser y links:

Dejo el repositorio de AtaJs, donde también están alguno de los ejemplos que vimos. De paso, dejo el listado de links útiles que comentaba, donde tienen todo lo necesario como para comenzar con el desarrollo de juegos con Phaser!!

- _Repo de AtaJs (con ejemplos y el juego de Ata)_
 https://gitlab.com/marcomaza92/atajs

- _Pagina de Phaser:_
 http://phaser.io/

- _Pagina de la documentación de Phaser_
 https://photonstorm.github.io/phaser3-docs/index.html

- _Pagina donde conseguir free assets (como para empezar)_
 https://opengameart.org/
    
 (en esta pagina hay audios, imágenes, texturas, etc)

- _El nuevo IDE de phaser (armar juegos al estilo de GameMaker o Constructor)_
 https://phasereditor2d.com/

- _¿Dónde podemos publicar nuestro juego?_
 https://itch.io/

 (tambien tiene información sobre GameJams que se realizan durante el año. La mayoría son online, y con alguna temática, si alguien se prende podemos hacer un grupo de esto y unirnos a las JAM!!)

- _Otra opcion para publicar gratuitamente:_
 https://glitch.com/

- _Algunas herramientas útiles para poder armar tus propios juegos_
 https://www.audacityteam.org/download/ (para armar/editar/compilar sonidos)

 https://www.mapeditor.org/ (permite armar niveles con mapas de textura, algo que Phaser tiene incorporado, utilizando el formato de Tiled como uno de sus standares)

 https://www.codeandweb.com/texturepacker (Para armar spritesheets o atlas)

 https://www.pixilart.com/ (una tool copada para armar diseños rapidos)

Hay un libro tmb que tengo que es de diseño de videojuegos (@mmaza) no recuerdo el nombre ahora, pero ayuda mucho para saber como encarar el desarrollo de un juego, desde el punto de vista del diseñador (no del diseñador gráfico, sino del diseñador/arquitecto del juego)

No hay nada que no haya podido buscar en google, hay mucha info, comunidad es grande, y es fácil de aprender, intuitivo y podes sacar un juego como AtaJs en muy poco tiempo!!

**Comment by elmiguedev** [comment]
Nunca fue maza ese jajaja

**Comment by homer0** [comment]
Charla realizada en la [edición 29](
https://www.meetup.com/Beer-js-Cordoba/events/260707969/) 🍻

**Comment by elmiguedev** [comment]
Mas allá de que esté cerrada la issue, dejo info sobre phaser y links:

Dejo el repositorio de AtaJs, donde también están alguno de los ejemplos que vimos. De paso, dejo el listado de links útiles que comentaba, donde tienen todo lo necesario como para comenzar con el desarrollo de juegos con Phaser!!

- _Repo de AtaJs (con ejemplos y el juego de Ata)_
 https://gitlab.com/marcomaza92/atajs

- _Pagina de Phaser:_
 http://phaser.io/

- _Pagina de la documentación de Phaser_
 https://photonstorm.github.io/phaser3-docs/index.html

- _Pagina donde conseguir free assets (como para empezar)_
 https://opengameart.org/
    
 (en esta pagina hay audios, imágenes, texturas, etc)

- _El nuevo IDE de phaser (armar juegos al estilo de GameMaker o Constructor)_
 https://phasereditor2d.com/

- _¿Dónde podemos publicar nuestro juego?_
 https://itch.io/

 (tambien tiene información sobre GameJams que se realizan durante el año. La mayoría son online, y con alguna temática, si alguien se prende podemos hacer un grupo de esto y unirnos a las JAM!!)

- _Otra opcion para publicar gratuitamente:_
 https://glitch.com/

- _Algunas herramientas útiles para poder armar tus propios juegos_
 https://www.audacityteam.org/download/ (para armar/editar/compilar sonidos)

 https://www.mapeditor.org/ (permite armar niveles con mapas de textura, algo que Phaser tiene incorporado, utilizando el formato de Tiled como uno de sus standares)

 https://www.codeandweb.com/texturepacker (Para armar spritesheets o atlas)

 https://www.pixilart.com/ (una tool copada para armar diseños rapidos)


Hay un libro tmb que tengo que es de diseño de videojuegos (@mmaza) no recuerdo el nombre ahora, pero ayuda mucho para saber como encarar el desarrollo de un juego, desde el punto de vista del diseñador (no del diseñador gráfico, sino del diseñador/arquitecto del juego)

No hay nada que no haya podido buscar en google, hay mucha info, comunidad es grande, y es fácil de aprender, intuitivo y podes sacar un juego como AtaJs en muy poco tiempo!!
