### ISSUE TITLE
Web Scraping en Node.js

### ISSUE THREAD

**Issue by torrescristian** [beerjs/cordoba#52]
La idea es dar una introducción al WebScraping con Puppeteer, y si veo que me da el tiempo QA Automation con Puppeteer + Jest

**Comment by BrodaNoel** [comment]
@torrescristian y si te da el tiempo, hay algo de Server Side Rendering con Puppeter, si mal no recuerdo :D

**Comment by mdottavio** [comment]
Charla realizada en la edición 26
https://www.meetup.com/Beer-js-Cordoba/events/258159669/
🍻
