### ISSUE TITLE
Loopback Framework- Usos, evolución y alternativas

### ISSUE THREAD

**Issue by spersico** [beerjs/cordoba#53]
Charla introductoria de Loopback en su version 3 y casos donde recomiendo su uso. Además, hablo un poco de la nueva versión, y alternativas con las que jugué a la hora de crear una api completa dentro de Node.JS hoy en día.

**Comment by mdottavio** [comment]
Charla realizada en la edición 26
https://www.meetup.com/Beer-js-Cordoba/events/258159669/
🍻
