### ISSUE TITLE
Quasar Overview

### ISSUE THREAD

**Issue by cbullokles** [beerjs/cordoba#54]
Rapida introduccion para crear aplicaciones en Quasar (que usa Vue de fondo).
Como crear una app simple que consume una API rest y empaquetarla para distintos entornos mobile

**Comment by tretapey** [comment]
+1 a esta charla

**Comment by homer0** [comment]
Charla realizada en la [edición 27](
https://www.meetup.com/Beer-js-Cordoba/events/258993697/) 🍻
