### ISSUE TITLE
Web Components con Stencil

### ISSUE THREAD

**Issue by joelalejandro** [beerjs/cordoba#55]
La idea de la charla es hablar un poco del estado actual de Web Components, y de Stencil, una librería para crear Web Components portables a aplicaciones en vanilla-JS, Vue, React, Ember y Angular.

### Outline

- ¿Qué es un Web Component?
- Polymer
- Custom Elements API
- Stencil, estructura y diseño de un componente
- Portabilidad

**Comment by homer0** [comment]
Charla realizada en la [edición 27](
https://www.meetup.com/Beer-js-Cordoba/events/258993697/) 🍻
