### ISSUE TITLE
You don't need JavaScript 😘

### ISSUE THREAD

**Issue by ataschz** [beerjs/cordoba#57]
La charla giraria en torno a la exploracion de los motivos que nos llevaron a utilizar a **JavaScript** como lenguaje principal de desarrollo y el porque actualmente, aun teniendo muchisimas alternativas, seguimos utilizandolo sin culpa.

**Topicos principales:**

¿Porque usamos JS?
¿Si no es JS, que entonces?
¿Realmente vale la pena cambiar JS por otro lenguaje?
Un ejemplo del mundo real: ReasonML

**Comment by ataschz** [comment]
@mdottavio fecha estimada... Junio/Julio 2019.

**Comment by homer0** [comment]
Cerrada hasta que @atasanchez tenga disponibilidad de nuevo.
