### ISSUE TITLE
CI para prototyping

### ISSUE THREAD

**Issue by cbullokles** [beerjs/cordoba#59]
Como hacer CI para pequeños prototipos y llegar de GitLab a Google en un commit.

**Comment by elmiguedev** [comment]
Quiero mas info de esto

**Comment by homer0** [comment]
Charla realizada en la [edición 31](
https://www.meetup.com/Beer-js-Cordoba/events/262579889/) 🍻

**Links:**

- https://www.youtube.com/watch?v=WPPlzlojXTU
- https://gitlab.com/bulli-talks/node-ci
- http://bit.ly/beerjscba-31-ci4p-slides
