### ISSUE TITLE
JavaScript Fundamentals - this & Object Prototypes

### ISSUE THREAD

**Issue by emiacc** [beerjs/cordoba#60]
La idea es continuar con la serie de **JavaScript Fundamentals** y hablar un poco de los siguientes temas:

Utilidad del _this_
Confuciones típicas 
Default Binding
Binding Implícito
Binding Explícito
_Object Prototypes_
Herencia "_Prototypal_"

Parte de la serie JavaScript Fundamentals #30

**Comment by homer0** [comment]
@emiacc Hola! Te interesaría dar esta charla en el próximo BeerJS? Si estas en [**el slack**](https://beerjscba.herokuapp.com), tirame un ping o tu email y charlamos.

Saludos!

**Comment by homer0** [comment]
Charla realizada en la [edición 30](
https://www.meetup.com/Beer-js-Cordoba/events/261714877/) 🍻
