### ISSUE TITLE
Desarrollo de juegos con JS - Parte 2 (Phaser - Socket.io)

### ISSUE THREAD

**Issue by elmiguedev** [beerjs/cordoba#62]
La idea es la continuación de la charla anterior (en la que se mostraba qué es Phaser) y complementarla con algunas features más e incluyendo la integración con Socket.io para juegos "online"

**Comment by homer0** [comment]
Charla realizada en la [edición 33](
https://www.meetup.com/Beer-js-Cordoba/events/263557417/) 🍻

- [Video](https://www.youtube.com/watch?v=Qa7dWYL0-Jg)
- [Slides](https://view.genial.ly/5d5ee57d83d45a0fdcc9c55e/presentation-beerjs-33-phaser)
