### ISSUE TITLE
Creando un bot de Telegram con Node.js

### ISSUE THREAD

**Issue by jbrizio** [beerjs/cordoba#64]
La idea sería dar una breve introducción sobre:
- ¿Qué es Telegram y que nos ofrece su API a los desarrolladores?
- ¿Qué son los chatbots y para que sirven?
- Casos prácticos de uso

Como caso práctico se tomará el siguiente ejemplo:
https://github.com/jbrizio/red-bus-telegram-bot/

**Comment by elmiguedev** [comment]
Me parece muy copada la charla! Nosotros trabajamos con bots de telegram y son súper útiles!

@jbrizio agregaría a la charla, si no es que se extiende mucho, posibilidades gratuitas de publicarlas, o al menos baratas y sencillas

**Comment by elmiguedev** [comment]
@marcomaza92 tageala como charla

**Comment by jbrizio** [comment]
@mmoyano16 Si, podría comentar brevemente sobre las diferentes opciones, desde las más comunes hasta las más complejas y costosas.

**Comment by homer0** [comment]
Charla realizada en la [edición 31](
https://www.meetup.com/Beer-js-Cordoba/events/262579889/) 🍻

**Links:**

- https://www.youtube.com/watch?v=Z5TJuGKjv4M
- https://core.telegram.org/bots
- https://github.com/telegraf/telegraf
- https://speakerdeck.com/jbrizio/creating-a-bot-for-telegram-with-node-dot-js-and-migrating-to-aws
