### ISSUE TITLE
Como hacer APIs que no odiemos

### ISSUE THREAD

**Issue by spersico** [beerjs/cordoba#65]
_Titulo robado de un libro que (aún) no leí._

La idea es explicar que es JSONAPI, para que sirve, que alternativas hay, y un framework que en mi empresa estamos desarrollando, que permite hacer APIs que cumplen con JSONAPI. Con caso práctico incluído, si me da el tiempo.

Link al framework:
[JSONAPI-TS](https://github.com/ebryn/jsonapi-ts)

**Comment by homer0** [comment]
Charla realizada en la [edición 30](
https://www.meetup.com/Beer-js-Cordoba/events/261714877/) 🍻
