### ISSUE TITLE
Micro Frontends - El concepto de microservicios en el front

### ISSUE THREAD

**Issue by Canopix** [beerjs/cordoba#66]
La idea principal de esta charla es dar a conocer el concepto de Micro frontends, definirlo, explicar de que se trata y mostrar algun caso de estudio. 

Es una charla introductoria,  el proposito no es dar una revision super profunda al respecto, sino mas bien, poder presentar el concepto, caracteristicas, ventajas y desventajas, etc.

**Comment by Canopix** [comment]
Voy a patear esta charla para la proxima BeerJs si es posible (Tampco se si me habian elegido para esta sesion de la misma) debido a organizacion personal en relacion a un viaje. Ya avise en el Slack pero lo dejo por aca.

**Comment by homer0** [comment]
Charla realizada en la [edición 32](
https://www.meetup.com/Beer-js-Cordoba/events/263266279/) 🍻

**Links**:
- https://www.youtube.com/watch?v=0YNDKEP5_Dk
