### ISSUE TITLE
Getting Started with Svelte 3

### ISSUE THREAD

**Issue by Charca** [beerjs/cordoba#67]
Charla introductoria a Svelte 3 y Sapper.
Temas a cubrir:

- Qué distingue Svelte de la gran mayoría de los otros frameworks.
- Cómo funciona un framework runtime-less.
- Cómo se compara con React y Vue.
- Demos y recursos para arrancar con Svelte.

**Comment by homer0** [comment]
Charla realizada en la [edición 32](
https://www.meetup.com/Beer-js-Cordoba/events/263266279/) 🍻

**Links**:
- https://www.youtube.com/watch?v=N5g0dFfz9iQ
