### ISSUE TITLE
Diseñando la arquitectura de una batería de tests E2E

### ISSUE THREAD

**Issue by joelalejandro** [beerjs/cordoba#69]
La idea es comentar una experiencia que tuve en @counterfactual a la hora de testear todo el stack a través de un browser con Selenium.

Más allá de la elección tecnológica, el desafío fue *cómo escribir tests que se enfoquen en las acciones del usuario a alto nivel* y no en el nivel de detalle fino que requiere trabajar con soluciones de este estilo.

En esta charla voy a mostrar cómo implementar un componente _TestBrowser_ que haga las operaciones que necesitamos luego para escribir tests concretos, legibles y breves.

**Comment by homer0** [comment]
Charla realizada en la [edición 33](
https://www.meetup.com/Beer-js-Cordoba/events/263557417/) 🍻

- [Video](https://www.youtube.com/watch?v=hU29LN7xyPk)
- [Slides](https://slides.com/joelalejandrovillarrealbertoldi/herramientas-e2e)
