### ISSUE TITLE
Javascript accesible

### ISSUE THREAD

**Issue by fermercadal** [beerjs/cordoba#72]
Hola!

Estoy armando una charla sobre **Accesibilidad web en Javascript,** basándome en las siguientes premisas:

1- Debido a la popularidad actual de los frameworks js, en gran medida ser un desarrollador JS significa hoy ser un desarrollador de UIs, y para que esas interfaces funcionen realmente es fundamental que sean accesibles.

2- En el desarrollo de interfaces, Javascript nos permite reinventar muchos elementos nativos de HTML, como pueden ser un _select_ o un _button_ pero debemos conocer como funcionan completamente para no caer en el error de recrear sólo la parte visual.

El objetivo principal es destacar de que manera podemos mejorar _(y también empeorar)_ la accesibilidad de una UI utilizando Javascript.

A nivel técnico, me gustaría abordar:

Soporte para navegación con teclado:
- Uso del Focus
- Uso de ARIA roles

Soporte para lectores de pantalla:
- Uso del Texto alternativo
- Labeling (Nativo + ARIA labels)

Qué les parece?

**Comment by homer0** [comment]
Charla realizada en la [edición 40](
https://www.meetup.com/Beer-js-Cordoba/events/270679428/) 🍻
